### ISSUE TITLE
convert to igraph  error when node has more than one label - similar to closed issue #43

### ISSUE THREAD

**Issue by dfgitn4j** [neo4j-rstats/neo4r#47] opened 2019-02-11 22:59 UTC
Differing number of rows error if the node has more than one label on it - e.g.: 
```
l<-"MATCH (p:Person {name: 'Tom Hanks'}) SET p:Test return p" %>% call_neo4j(con, type = "row")
G <-"MATCH a=(p:Person {name: 'Tom Hanks'})-[r:ACTED_IN]->(m:Movie) RETURN a;" %>% call_neo4j(con, type = "graph") %>% convert_to('igraph')

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 14, 13
```

You can see that in unnest_nodes that the lab and df data frames have different lengths:

![2019-02-11_16-50-09](https://user-images.githubusercontent.com/36545410/52599420-2a97d180-2e1e-11e9-84ef-c73fba6d29f1.jpg)

**Comment by ColinFay** [comment] 2019-02-13 08:23
@dfgitn4j Hey Dan, 

This is linked to #46, this should be good by now : 

``` r
library(neo4r)
con <- neo4j_api$new(url = "http://localhost:7474", 
                     user = "neo4j", password = "neo4j")

l <-"MATCH (p:Person {name: 'Tom Hanks'}) SET p:Test return p" %>% call_neo4j(con, type = "row")
saveRDS(l, "inst/tests/testthat/movies_rows.RDS")
#> Warning in gzfile(file, mode): cannot open compressed file 'inst/tests/
#> testthat/movies_rows.RDS', probable reason 'No such file or directory'
#> Error in gzfile(file, mode): cannot open the connection
l
#> $p
#> # A tibble: 1 x 2
#>    born name     
#>   <int> <chr>    
#> 1  1956 Tom Hanks
#> 
#> attr(,"class")
#> [1] "neo"  "neo"  "list"

G <-"MATCH a=(p:Person {name: 'Tom Hanks'})-[r:ACTED_IN]->(m:Movie) RETURN a;" %>% 
  call_neo4j(con, type = "graph") 
saveRDS(G, "inst/tests/testthat/movies_graph.RDS")
#> Warning in gzfile(file, mode): cannot open compressed file 'inst/tests/
#> testthat/movies_graph.RDS', probable reason 'No such file or directory'
#> Error in gzfile(file, mode): cannot open the connection

G$relationships %>%
  unnest_relationships()
#> # A tibble: 20 x 5
#>    id    type     startNode endNode roles              
#>    <chr> <chr>    <chr>     <chr>   <chr>              
#>  1 18917 ACTED_IN 13225     13313   Rep. Charlie Wilson
#>  2 18923 ACTED_IN 13225     13316   Jimmy Dugan        
#>  3 18921 ACTED_IN 13225     13315   Hero Boy           
#>  4 18921 ACTED_IN 13225     13315   Father             
#>  5 18921 ACTED_IN 13225     13315   Conductor          
#>  6 18921 ACTED_IN 13225     13315   Hobo               
#>  7 18921 ACTED_IN 13225     13315   Scrooge            
#>  8 18921 ACTED_IN 13225     13315   Santa Claus        
#>  9 18902 ACTED_IN 13225     13304   Chuck Noland       
#> 10 18891 ACTED_IN 13225     13298   Jim Lovell         
#> 11 18871 ACTED_IN 13225     13284   Paul Edgecomb      
#> 12 18824 ACTED_IN 13225     13265   Dr. Robert Langdon 
#> 13 18815 ACTED_IN 13225     13259   Zachry             
#> 14 18815 ACTED_IN 13225     13259   Dr. Henry Goose    
#> 15 18815 ACTED_IN 13225     13259   Isaac Sachs        
#> 16 18815 ACTED_IN 13225     13259   Dermot Hoggins     
#> 17 18777 ACTED_IN 13225     13239   Mr. White          
#> 18 18765 ACTED_IN 13225     13232   Joe Banks          
#> 19 18758 ACTED_IN 13225     13227   Sam Baldwin        
#> 20 18751 ACTED_IN 13225     13221   Joe Fox

G$relationships %>%
  unnest_relationships()
#> # A tibble: 20 x 5
#>    id    type     startNode endNode roles              
#>    <chr> <chr>    <chr>     <chr>   <chr>              
#>  1 18917 ACTED_IN 13225     13313   Rep. Charlie Wilson
#>  2 18923 ACTED_IN 13225     13316   Jimmy Dugan        
#>  3 18921 ACTED_IN 13225     13315   Hero Boy           
#>  4 18921 ACTED_IN 13225     13315   Father             
#>  5 18921 ACTED_IN 13225     13315   Conductor          
#>  6 18921 ACTED_IN 13225     13315   Hobo               
#>  7 18921 ACTED_IN 13225     13315   Scrooge            
#>  8 18921 ACTED_IN 13225     13315   Santa Claus        
#>  9 18902 ACTED_IN 13225     13304   Chuck Noland       
#> 10 18891 ACTED_IN 13225     13298   Jim Lovell         
#> 11 18871 ACTED_IN 13225     13284   Paul Edgecomb      
#> 12 18824 ACTED_IN 13225     13265   Dr. Robert Langdon 
#> 13 18815 ACTED_IN 13225     13259   Zachry             
#> 14 18815 ACTED_IN 13225     13259   Dr. Henry Goose    
#> 15 18815 ACTED_IN 13225     13259   Isaac Sachs        
#> 16 18815 ACTED_IN 13225     13259   Dermot Hoggins     
#> 17 18777 ACTED_IN 13225     13239   Mr. White          
#> 18 18765 ACTED_IN 13225     13232   Joe Banks          
#> 19 18758 ACTED_IN 13225     13227   Sam Baldwin        
#> 20 18751 ACTED_IN 13225     13221   Joe Fox

G %>% 
  unnest_graph()
#> $nodes
#> # A tibble: 14 x 7
#>    id    value  tagline                    title      released  born name  
#>    <chr> <chr>  <chr>                      <chr>         <int> <int> <chr> 
#>  1 13313 Movie  A stiff drink. A little m… Charlie W…     2007    NA <NA>  
#>  2 13225 Person <NA>                       <NA>             NA  1956 Tom H…
#>  3 13225 Test   <NA>                       <NA>             NA  1956 Tom H…
#>  4 13316 Movie  Once in a lifetime you ge… A League …     1992    NA <NA>  
#>  5 13315 Movie  This Holiday Season… Beli… The Polar…     2004    NA <NA>  
#>  6 13304 Movie  At the edge of the world,… Cast Away      2000    NA <NA>  
#>  7 13298 Movie  Houston, we have a proble… Apollo 13      1995    NA <NA>  
#>  8 13284 Movie  Walk a mile you'll never … The Green…     1999    NA <NA>  
#>  9 13265 Movie  Break The Codes            The Da Vi…     2006    NA <NA>  
#> 10 13259 Movie  Everything is connected    Cloud Atl…     2012    NA <NA>  
#> 11 13239 Movie  In every life there comes… That Thin…     1996    NA <NA>  
#> 12 13232 Movie  A story of love, lava and… Joe Versu…     1990    NA <NA>  
#> 13 13227 Movie  What if someone you never… Sleepless…     1993    NA <NA>  
#> 14 13221 Movie  At odds in life... in lov… You've Go…     1998    NA <NA>  
#> 
#> $relationships
#> # A tibble: 20 x 5
#>    id    type     startNode endNode roles              
#>    <chr> <chr>    <chr>     <chr>   <chr>              
#>  1 18917 ACTED_IN 13225     13313   Rep. Charlie Wilson
#>  2 18923 ACTED_IN 13225     13316   Jimmy Dugan        
#>  3 18921 ACTED_IN 13225     13315   Hero Boy           
#>  4 18921 ACTED_IN 13225     13315   Father             
#>  5 18921 ACTED_IN 13225     13315   Conductor          
#>  6 18921 ACTED_IN 13225     13315   Hobo               
#>  7 18921 ACTED_IN 13225     13315   Scrooge            
#>  8 18921 ACTED_IN 13225     13315   Santa Claus        
#>  9 18902 ACTED_IN 13225     13304   Chuck Noland       
#> 10 18891 ACTED_IN 13225     13298   Jim Lovell         
#> 11 18871 ACTED_IN 13225     13284   Paul Edgecomb      
#> 12 18824 ACTED_IN 13225     13265   Dr. Robert Langdon 
#> 13 18815 ACTED_IN 13225     13259   Zachry             
#> 14 18815 ACTED_IN 13225     13259   Dr. Henry Goose    
#> 15 18815 ACTED_IN 13225     13259   Isaac Sachs        
#> 16 18815 ACTED_IN 13225     13259   Dermot Hoggins     
#> 17 18777 ACTED_IN 13225     13239   Mr. White          
#> 18 18765 ACTED_IN 13225     13232   Joe Banks          
#> 19 18758 ACTED_IN 13225     13227   Sam Baldwin        
#> 20 18751 ACTED_IN 13225     13221   Joe Fox            
#> 
#> attr(,"class")
#> [1] "neo"  "list"

G %>% 
  convert_to("igraph")
#> Error in graph_from_data_frame(d = unnested_res$relationships, directed = TRUE, : Duplicate vertex names
```

<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by ColinFay** [comment] 2019-02-13 08:53
Hey Dan, 

The first issue is linked to #47, and should be correct by now, BUT, there is a conceptual issue with this request. 

Unnesting a dataframe means that we are moving to a one-row-by-combination format, but here we have two labels for one ID, so two combinations: 

``` r
res$nodes
# A tibble: 13 x 3
   id    label     properties
   <chr> <list>    <list>    
 1 13313 <chr [1]> <list [3]>
 2 13225 <chr [2]> <list [2]>
 [...]

res$nodes$label
[[1]]
[1] "Movie"

[[2]]
[1] "Person" "Test" 

[...]
```
Which means that the result of the unnesting will look like this : 

```
nodes_tbl %>% unnest(label, .drop = FALSE)
# A tibble: 14 x 3
   id    properties value 
   <chr> <list>     <chr> 
 1 13313 <list [3]> Movie 
 2 13225 <list [2]> Person
 3 13225 <list [2]> Test  
[...]
```
So far so good but the issue is that this id is now repeated twice, as we are unnesting and have all the combination ID-labels. 

It's impossible for igraph to handle a column with repeated IDs. 

In the latest commit, i've implemented that only the first label is taken (with a warning). It's also noted in the documentation. 

Do you have another idea on how to handle that? 

``` r
``` r
library(neo4r)
con <- neo4j_api$new(url = "http://localhost:7474", 
                     user = "neo4j", password = "neo4j")

l <-"MATCH (p:Person {name: 'Tom Hanks'}) SET p:Test return p" %>% call_neo4j(con, type = "row")

G <-"MATCH a=(p:Person {name: 'Tom Hanks'})-[r:ACTED_IN]->(m:Movie) RETURN a;" %>% 
  call_neo4j(con, type = "graph") 

a <- G$relationships %>%
  unnest_relationships()

a <-G$relationships %>%
  unnest_relationships()

a <-G %>% 
  unnest_graph()
#> Warning: Nodes with more than one label will only keep the first label.

a <- G %>% 
  convert_to("igraph") 
#> Warning: Nodes with more than one label will only keep the first label.
```

**Comment by ColinFay** [comment] 2019-02-14 09:25
Ok, removing the convert_to function for now until we find a good way to implement that. 

I wrote a how to for manual conversion https://github.com/neo4j-rstats/neo4r#convert-for-common-graph-packages and https://neo4j-rstats.github.io/user-guide/convert-for-common-graph-packages.html

**Comment by ColinFay** [comment] 2019-06-03 10:44
convert_to is no longer there, closing for now

**Closed by ColinFay** 2019-06-03 10:44 UTC
